# -*- coding: utf-8 -*-
"""
更新 XOS 功能点清单：
  1) 新增「完成度」列（插在「是否开发」与「更新时间」之间）
  2) 将序号 1-120（内存管理 / 物理内存管理）替换为已实现的真实功能点，
     并回填「详情描述」「是否开发」「完成度」「更新时间」
"""
import os
import openpyxl
from openpyxl.styles import Font, Alignment, PatternFill
from openpyxl.utils import get_column_letter

XLSX = r'D:\新系统开发需求文档\XOS_操作系统_10000功能点清单.xlsx'
STAMP = '2026-09-24'

# ---------------------------------------------------------------------------
# 120 个已实现的物理内存管理功能点
# (功能点名称, 实现位置, 功能说明, 技术实现, 验收标准)
# ---------------------------------------------------------------------------
FP = [
# ---------------- 一、E820 物理内存探测（1-34）----------------
("BIOS E820 内存探测（INT 15h EAX=E820h）", "boot/stage2.S : detect_e820",
 "在实模式下循环调用 BIOS INT 15h 获取物理内存映射表，是内核获知可用内存的唯一权威来源。",
 "EAX=0xE820，EDX=0x534D4150('SMAP')，ECX=24，ES:DI=缓冲区；循环至 EBX=0 或 CF=1。缓冲区固定于物理地址 0x0500。",
 "VirtualBox 128MB 内存下探测到 8 条映射条目，与虚拟机设置一致。"),
("E820 探测失败回退（INT 15h AH=88h）", "boot/stage2.S : detect_fallback",
 "当 BIOS 完全不支持 E820 时，用传统 AH=88h 接口取得 1MB 以上内存量，保证老机器仍可启动。",
 "AH=88h 返回 AX=1MB 以上内存 KB 数；据此合成「0~640KB 可用」与「1MB~1MB+N 可用」两条映射。",
 "在 E820 返回 0 条时自动进入回退分支，映射表至少含 2 条可用区。"),
("E820 条目缓冲区固定地址管理", "boot/stage2.S : E820_BUF=0x0500",
 "选定 0x0500 作为 BIOS 写入内存映射的缓冲区，避开 0x7C00 引导扇区与 0x7E00 Stage2。",
 "0x0500~0x0B00 共 1536 字节，可容纳 64 条 24 字节条目，不与任何已用低端内存冲突。",
 "连续 64 条探测后缓冲区未越界（末地址 0x0AE8 < 0x7C00）。"),
("E820 条目计数存储", "boot/stage2.S : E820_CNT=0x04F0",
 "将实际取得的条目数以 16 位整数写入固定地址 0x04F0，供保护模式下的内核读取。",
 "写于探测循环结束后；地址与缓冲区同处低端内存，保护模式下平坦段可直接访问。",
 "内核 e820_init() 读到的条目数与 Stage2 实际探测数一致。"),
("E820 条目数上限保护", "boot/stage2.S : E820_MAX=64 / include/e820.h",
 "限制最大处理条目数，防止异常 BIOS 返回无限条目导致缓冲区溢出。",
 "每取一条前比较计数器与 E820_MAX，达到上限立即终止循环；内核侧再次以 E820_MAX_ENTRIES 截断。",
 "构造超量条目场景时不会越界写，计数器不超过 64。"),
("'SMAP' 签名校验", "boot/stage2.S : cmpl $0x534D4150, %eax",
 "校验 BIOS 是否真正支持 E820，避免把无效返回值当作内存映射解析。",
 "INT 15h 返回后比较 EAX 与 0x534D4150，不等则立即终止探测并进入回退分支。",
 "不支持 E820 的 BIOS 会走到回退路径，不会产生脏映射数据。"),
("E820 返回长度校验", "boot/stage2.S : testl %ecx, %ecx",
 "校验 BIOS 实际写入的字节数，ECX=0 表示本次未返回有效数据，应终止。",
 "INT 15h 返回后测试 ECX，为 0 则跳到 .e820_done。",
 "ECX=0 的异常返回不会污染映射表。"),
("E820 延续值 EBX 循环终止判定", "boot/stage2.S : testl %ebx, %ebx",
 "依据 E820 协议用 EBX 作为迭代游标，EBX 归零表示枚举完毕。",
 "每次 INT 15h 后测试 EBX，非 0 则继续下一轮，为 0 则结束。",
 "枚举完整结束且无重复条目。"),
("空长度条目过滤", "kernel/e820.c : e820_init()",
 "丢弃 length==0 的条目，这类条目无实际意义且会干扰合并与统计。",
 "e820_init 逐条检查 e->length，为 0 直接跳过不入表。",
 "映射表中不存在长度为零的条目。"),
("非法类型条目过滤", "kernel/e820.c : e820_init()",
 "丢弃 type==0 或 type>5 的条目，防止未知类型污染统计口径。",
 "条件 (e->type == 0 || e->type > E820_BAD) 时跳过。",
 "映射表所有条目的类型均落在 1~5 闭区间。"),
("可用内存类型识别（Type 1）", "kernel/e820.c : E820_USABLE",
 "识别 BIOS 标记为 Usable 的物理区间，作为页分配器的可用内存来源。",
 "type==1 的区间累加进 usable_bytes 并参与 pmm_init 的区间释放。",
 "128MB 虚拟机中可用内存统计为 130623KB。"),
("保留内存类型识别（Type 2）", "kernel/e820.c : E820_RESERVED",
 "识别 Reserved 区间（含 VGA、BIOS ROM、PCI 空洞），这些区域绝不可分配。",
 "type==2 累加进 reserved_bytes，不参与可用区释放。",
 "保留内存统计为 329KB（含 0xA0000-0x100000 等）。"),
("ACPI 可回收内存识别（Type 3）", "kernel/e820.c : E820_ACPI_RECLAIM",
 "识别 ACPI Reclaimable 区间，供后续 ACPI 子系统在读取表后回收。",
 "type==3 累加进 acpi_reclaim_bytes，当前阶段不释放给分配器。",
 "ACPI 可回收内存统计为 64KB。"),
("ACPI NVS 内存识别（Type 4）", "kernel/e820.c : E820_ACPI_NVS",
 "识别 ACPI NVS 区间，该区域必须始终保留不可回收。",
 "type==4 累加进 acpi_nvs_bytes。",
 "ACPI NVS 统计值正确（虚拟机下为 0KB）。"),
("坏内存类型识别（Type 5）", "kernel/e820.c : E820_BAD",
 "识别 BIOS 标记的坏内存页，永久排除在分配器之外。",
 "type==5 累加进 bad_bytes。",
 "坏内存统计值正确（虚拟机下为 0KB）。"),
("内存类型名称映射", "kernel/e820.c : e820_type_name()",
 "把数值类型转换为可读字符串，供调试输出与日志使用。",
 "switch 分发到 Usable/Reserved/ACPI-Reclaim/ACPI-NVS/Bad/Unknown。",
 "控制台映射表输出中类型列显示为英文名称而非数字。"),
("E820 扩展属性位 ENABLED 解析", "include/e820.h : E820_ATTR_ENABLED=0x1",
 "解析条目第 20 字节的 ACPI 扩展属性，判断该区间是否被固件标记为可交给 OS 使用。",
 "e820_dump 中对 type==1 且 (acpi & 0x1) 的条目追加 (enabled) 标记。",
 "映射表输出中可用区正确显示 enabled 标记。"),
("E820 扩展属性位 NONVOLATILE 解析", "include/e820.h : E820_ATTR_NONVOLATILE=0x2",
 "解析非易失内存属性位，为后续持久内存支持预留判定依据。",
 "以位掩码常量定义，供上层按需查询。",
 "常量定义与 ACPI 规范一致，可被上层引用。"),
("映射表按基址升序排序", "kernel/e820.c : e820_sort()",
 "把 BIOS 返回的乱序条目按基址升序重排，为合并与区间查找提供前提。",
 "采用插入排序（条目数 ≤ 64，复杂度可忽略），逐条前移到位。",
 "排序后任意相邻两条满足 map[i-1].base <= map[i].base。"),
("相邻同类型区间合并", "kernel/e820.c : e820_merge()",
 "把首尾相接且类型相同的区间合并为一条，减少条目数、简化后续遍历。",
 "判定 cur->base + cur->length == next->base 且类型相同，则长度相加。",
 "虚拟机上 8 条原始条目合并后仍为 8 条（无相邻同类区间）。"),
("重叠同类型区间并集合并", "kernel/e820.c : e820_merge()",
 "处理 BIOS 返回的区间重叠情形，取并集避免统计重复计数。",
 "判定 next->base < cur->base + cur->length，取两者末端较大者作为新末端。",
 "构造重叠条目时合并结果覆盖完整且不重复计数。"),
("合并条目数统计", "kernel/e820.c : e820_merge() 返回值",
 "返回本次合并减少的条目数，用于诊断 BIOS 映射质量。",
 "记录合并前 map_count 并返回 before - after。",
 "无合并时返回 0，有合并时返回实际减少条数。"),
("总地址空间统计", "kernel/e820.c : e820_stats()",
 "累加全部条目的长度，得到 BIOS 描述的总地址空间。",
 "遍历时无条件 total_bytes += e->length。",
 "128MB 虚拟机统计为 131016KB。"),
("可用内存统计", "kernel/e820.c : mem_stats_t.usable_bytes",
 "汇总所有 Type 1 区间长度，是页分配器的可用内存上限依据。",
 "type==E820_USABLE 时累加并递增 usable_entries。",
 "统计值 130623KB，与 E820 条目明细相加一致。"),
("保留内存统计", "kernel/e820.c : mem_stats_t.reserved_bytes",
 "汇总所有 Type 2 区间长度，用于核对内存账目完整性。",
 "type==E820_RESERVED 时累加。",
 "保留内存 329KB，可用+保留+ACPI 与总地址空间账目平衡。"),
("ACPI 可回收内存统计", "kernel/e820.c : mem_stats_t.acpi_reclaim_bytes",
 "汇总 Type 3 区间长度，为 ACPI 子系统后续回收提供基准。",
 "type==E820_ACPI_RECLAIM 时累加。",
 "统计值 64KB。"),
("ACPI NVS 统计", "kernel/e820.c : mem_stats_t.acpi_nvs_bytes",
 "汇总 Type 4 区间长度，明确永久保留量。",
 "type==E820_ACPI_NVS 时累加。",
 "统计值正确且不被计入可用内存。"),
("坏内存统计", "kernel/e820.c : mem_stats_t.bad_bytes",
 "汇总 Type 5 区间长度，量化物理内存可靠性风险。",
 "type==E820_BAD 时累加。",
 "统计值正确且不被计入可用内存。"),
("1MB 以下可用内存统计", "kernel/e820.c : mem_stats_t.below_1m_usable",
 "单独统计 1MB 以下可用量，该区域受 BIOS/引导占用限制，需谨慎使用。",
 "对 base<1MB 的可用条目，按 min(end,1MB)-base 累加。",
 "虚拟机下为 639KB，与 0x0-0x9FC00 相符。"),
("最高可寻址地址统计", "kernel/e820.c : mem_stats_t.highest_addr",
 "取所有条目末端的最大值，用于确定受管物理内存上限。",
 "遍历中若 (base+length) > highest_addr 则更新。",
 "虚拟机下为 0x8000000（128MB）。"),
("可用页数换算", "kernel/e820.c : mem_stats_t.usable_pages",
 "把可用字节数按 4KB 换算为页数，直接对接页分配器口径。",
 "usable_pages = (u32)(usable_bytes >> 12)。",
 "统计为 32655 页，与 130623KB/4 一致。"),
("内存映射表调试打印", "kernel/e820.c : e820_dump()",
 "以对齐表格输出序号、基址、长度、类型，是启动阶段验证探测结果的主要手段。",
 "逐行输出，序号右对齐，地址以 8 位十六进制显示，可用区附加 enabled 标记。",
 "VirtualBox 启动后控制台完整显示 8 行映射且列对齐。"),
("映射表只读访问接口", "kernel/e820.c : e820_get()",
 "提供按索引安全取条目的接口，越界返回 NULL。",
 "if (index >= map_count) return NULL; 否则返回 &map[index]。",
 "越界索引返回 NULL，合法索引返回正确条目。"),
("映射表条目计数接口", "kernel/e820.c : e820_count()",
 "对外暴露当前映射表条目数，供统计与遍历循环边界使用。",
 "直接返回静态变量 map_count。",
 "返回值与 e820_dump 打印行数一致。"),

# ---------------- 二、PMM 页帧分配器（35-79）----------------
("页大小常量定义", "include/pmm.h : PAGE_SIZE=4096, PAGE_SHIFT=12",
 "定义 x86 标准 4KB 页粒度，作为全部内存管理的基准单位。",
 "PAGE_SIZE = 1u << PAGE_SHIFT，配套 PAGE_MASK 用于地址取整。",
 "编译期常量，与 x86 分页硬件页大小一致。"),
("页号与物理地址互换宏", "include/pmm.h : PHYS_TO_PAGE / PAGE_TO_PHYS",
 "在页号与物理地址之间无损转换，是位图索引与地址返回的桥梁。",
 "PHYS_TO_PAGE(a) = a >> 12；PAGE_TO_PHYS(p) = p << 12。",
 "双向转换满足 PAGE_TO_PHYS(PHYS_TO_PAGE(a)) == a & PAGE_MASK。"),
("页对齐向上取整宏", "include/pmm.h : PAGE_ALIGN_UP",
 "把任意字节地址向上对齐到页边界，用于区间末端计算。",
 "((x) + PAGE_SIZE - 1) & PAGE_MASK。",
 "输入 4097 输出 8192，输入 4096 输出 4096。"),
("页对齐向下取整宏", "include/pmm.h : PAGE_ALIGN_DOWN",
 "把任意字节地址向下对齐到页边界，用于区间起点计算。",
 "(x) & PAGE_MASK。",
 "输入 4095 输出 0，输入 8191 输出 4096。"),
("页对齐判定宏", "include/pmm.h : PAGE_IS_ALIGNED",
 "判断地址是否为页边界，用于释放接口入参合法性校验。",
 "((x) & (PAGE_SIZE - 1)) == 0。",
 "0x1000 判定为已对齐，0x1234 判定为未对齐。"),
("页帧位图数据结构", "kernel/pmm.c : bitmap[BITMAP_WORDS]",
 "以位图记录每一页的占用状态，1 字节管理 8 页，32768 页仅占 4KB。",
 "u32 bitmap[1024]，BITMAP_WORDS = PMM_MAX_PAGES/32；位号即页号。",
 "静态占用 4096 字节，覆盖 128MB 物理内存。"),
("位图置位（标记占用）", "kernel/pmm.c : bitmap_set()",
 "把指定页标记为已占用，并同步递增已用页计数。",
 "先 test_bit 判重，未占用才 set_bit 并 used_pages++。",
 "重复置位不会导致计数虚高。"),
("位图清位（标记空闲）", "kernel/pmm.c : bitmap_clear()",
 "把指定页标记为空闲，并同步递减已用页计数。",
 "先 test_bit 判在占用，才 clear_bit 并 used_pages--。",
 "重复清位不会导致计数为负。"),
("位图查询（占用判定）", "kernel/pmm.c : test_bit()",
 "查询单页占用状态，是分配与释放路径的公共判定。",
 "map[bit>>5] >> (bit&31) & 1。",
 "对已分配页返回 1，对空闲页返回 0。"),
("已用页计数维护", "kernel/pmm.c : used_pages",
 "维护全局已用页计数，避免每次统计都全表扫描位图。",
 "仅在位状态真正发生变化时增减，保证 O(1) 查询。",
 "分配 N 页后 used_pages 增加 N，释放后精确回落。"),
("受管物理内存上限确定", "kernel/pmm.c : pmm_init()",
 "取 BIOS 最高地址与内核硬上限（128MB）的较小者作为管理边界。",
 "limit = min(highest_addr, PMM_MAX_PHYS)，再向下页对齐。",
 "128MB 虚拟机下受管 32768 页。"),
("受管页总数计算", "kernel/pmm.c : total_pages",
 "由受管上限换算出位图有效位数，界定所有越界判定。",
 "total_pages = PHYS_TO_PAGE(managed_limit)，上限 PMM_MAX_PAGES。",
 "统计输出 Managed pages = 32768。"),
("依据 E820 释放可用区间", "kernel/pmm.c : pmm_init() 第 4 步",
 "遍历映射表把所有 Type 1 区间在位图中标记为空闲，是内存可用的关键一步。",
 "对每条可用条目调用 pmm_release_range(base, base+length)，并裁剪到 128MB 内。",
 "初始化后空闲页 32496 页（约 126MB）。"),
("低端 1MB 保留", "kernel/pmm.c : pmm_reserve_range(0, 0x100000)",
 "永久保留 0~1MB，覆盖引导程序、BIOS 数据区、E820 表、VGA 显存与内核栈。",
 "在释放可用区之后执行保留，确保即使 E820 声明可用也不会被分配。",
 "低端 256 页始终为占用状态，分配器不会返回 <1MB 的页。"),
("内核映像区保留", "kernel/pmm.c : KERNEL_RESERVE_BASE/END",
 "保留 0x10000~0x40000，保护内核代码段、只读数据、数据段与 .bss。",
 "以宏定义固定区间并调用 pmm_reserve_range；覆盖 Stage2 的 64KB 装载窗口及其后 BSS。",
 "分配器不会返回内核自身占用范围内的任何页。"),
("保留页计数", "kernel/pmm.c : reserved_pages",
 "统计不可分配的保留页数，用于向用户说明内存账目。",
 "reserved_pages = 低端 1MB 页数 + 内核映像区页数。",
 "统计输出 Reserved pages = 304。"),
("区间保留接口", "kernel/pmm.c : pmm_reserve_range()",
 "通用区间保留接口，半开区间 [start,end)，自动页对齐并裁剪边界。",
 "first=PAGE_ALIGN_DOWN(start)，last=PAGE_ALIGN_UP(end)，逐页 bitmap_set。",
 "保留任意区间后该区间内所有页 is_used 返回真。"),
("区间释放接口", "kernel/pmm.c : pmm_release_range()",
 "通用区间释放接口，用于把 E820 可用区纳入分配器管理。",
 "参数处理同保留接口，逐页 bitmap_clear。",
 "释放后区间内页可被正常分配。"),
("首个空闲页查找（字级扫描）", "kernel/pmm.c : pmm_find_first_free()",
 "以 32 位字为单位快速跳过全满区域，显著减少扫描次数。",
 "逐字比较是否等于 0xFFFFFFFF，不等才进入位级定位。",
 "128MB 位图最坏扫描 1024 个字，实测启动耗时可忽略。"),
("首个空闲页查找（位级定位）", "kernel/pmm.c : pmm_find_first_free()",
 "在非满字内定位最低位的空闲位，得到候选页号。",
 "取反后从低到高找第一个置位位，再校验页号小于 total_pages。",
 "返回的页号必然空闲且不越界。"),
("连续 n 页查找", "kernel/pmm.c : pmm_find_contiguous()",
 "按游程统计寻找连续空闲页块，满足 DMA 与页表等需连续物理内存的场景。",
 "n==1 退化为单页查找；否则遍历累计连续空闲数，达到 n 即返回起始页号。",
 "返回块内所有页均为空闲且物理连续。"),
("单页分配", "kernel/pmm.c : pmm_alloc_page()",
 "分配一页物理内存并返回其物理地址，失败返回 0。",
 "查找首个空闲页→置位→返回 PAGE_TO_PHYS(page)。",
 "返回地址页对齐、is_used 为真、空闲页数减 1。"),
("连续多页分配", "kernel/pmm.c : pmm_alloc_pages()",
 "分配连续 n 页物理内存，用于页表、DMA 缓冲等场景。",
 "查找连续块→逐页置位→返回首物理地址；n==0 或找不到返回 0。",
 "返回块内 n 页全部被标记占用且地址连续。"),
("零填充页分配", "kernel/pmm.c : pmm_alloc_page_zeroed()",
 "分配一页并清零，避免把上一使用者的残留数据泄漏给新使用者。",
 "调用 pmm_alloc_page 后对整页执行 memset(addr, 0, 4096)。",
 "返回页的全部 4096 字节均为 0。"),
("单页释放", "kernel/pmm.c : pmm_free_page()",
 "释放单页物理内存，含对齐、越界、重复释放、低端保护四重校验。",
 "依次校验对齐→范围→是否已占用→是否低于 1MB，全部通过才清位。",
 "合法释放返回 PMM_OK，异常路径返回对应错误码。"),
("连续多页释放", "kernel/pmm.c : pmm_free_pages()",
 "释放连续 n 页，逐页调用单页释放并短路返回首个错误。",
 "循环 pmm_free_page(phys + i*PAGE_SIZE)，任一失败立即返回该错误码。",
 "全部释放返回 PMM_OK，空闲页数增加 n。"),
("非对齐地址释放拒绝", "kernel/pmm.c : PMM_EINVAL",
 "拒绝释放非页对齐地址，防止误清相邻页导致内存账目错乱。",
 "!PAGE_IS_ALIGNED(phys) 时返回 PMM_EINVAL。",
 "传入 0x1234 返回 PMM_EINVAL（自检用例 7 覆盖）。"),
("重复释放拒绝", "kernel/pmm.c : PMM_EBUSY",
 "检测双重释放，避免空闲页计数被重复递减。",
 "目标页位为 0（已空闲）时返回 PMM_EBUSY。",
 "同一页连续释放两次，第二次返回 PMM_EBUSY（自检用例 5 覆盖）。"),
("低端内存释放保护", "kernel/pmm.c : page < PHYS_TO_PAGE(0x100000)",
 "禁止释放 1MB 以下页面，保护引导程序与 BIOS 数据结构不被回收复用。",
 "页号小于 256 时直接返回 PMM_EBUSY。",
 "释放 0x1000 返回 PMM_EBUSY（自检用例 8 覆盖）。"),
("越界页号拒绝", "kernel/pmm.c : page >= total_pages",
 "拒绝操作超出受管范围的页号，防止位图越界访问。",
 "页号不小于 total_pages 时按错误处理，is_used 对越界页恒返回占用。",
 "对 0xFFFFFFFF 的查询与释放均不产生越界写。"),
("分配失败返回 0 语义", "kernel/pmm.c : 返回值约定",
 "统一以 0 表示分配失败，因 0 地址永远属于保留的低端内存，不会与合法分配冲突。",
 "分配函数在无可用页时返回 0，调用方仅需判零。",
 "内存耗尽场景下返回 0 且不修改位图。"),
("空闲页数查询", "kernel/pmm.c : pmm_free_page_count()",
 "以 O(1) 返回当前空闲页数，供上层做内存压力判断。",
 "total_pages - used_pages，带下溢保护。",
 "统计输出 Free pages = 32496。"),
("已用页数查询", "kernel/pmm.c : pmm_used_pages()",
 "返回当前已用（含保留）页数。",
 "直接返回 used_pages 计数。",
 "统计输出 Used pages = 272。"),
("受管总页数查询", "kernel/pmm.c : pmm_total_pages()",
 "返回分配器管理的页总数。",
 "直接返回 total_pages。",
 "统计输出 Managed pages = 32768。"),
("保留页数查询", "kernel/pmm.c : pmm_reserved_pages()",
 "返回不可分配的保留页数。",
 "直接返回 reserved_pages。",
 "统计输出 Reserved pages = 304。"),
("区间内空闲页计数", "kernel/pmm.c : pmm_count_free_in_range()",
 "统计任意区间内的空闲页数，用于内存碎片评估与预留校验。",
 "区间页对齐裁剪后逐页 test_bit 累加空闲数。",
 "对全部受管区间统计结果与 pmm_free_page_count 一致。"),
("自检用例 1：单页分配地址对齐", "kernel/pmm.c : pmm_selftest() case 1",
 "验证分配返回的地址非零且严格页对齐。",
 "a = pmm_alloc_page()；判 a!=0 且 PAGE_IS_ALIGNED(a)，否则返回 1。",
 "启动日志显示 PASS，未返回 1。"),
("自检用例 2：分配后占用标记生效", "kernel/pmm.c : pmm_selftest() case 2",
 "验证分配后该页确实被标记为占用。",
 "对刚分配的地址调用 pmm_is_used，应为真，否则返回 2。",
 "启动日志 PASS。"),
("自检用例 3：分配后空闲页数递减", "kernel/pmm.c : pmm_selftest() case 3/4",
 "验证分配动作使空闲页计数精确减少 1。",
 "记录分配前空闲数，分配后再查，应等于 before-1，否则返回 4。",
 "启动日志 PASS。"),
("自检用例 4：释放后空闲页数恢复", "kernel/pmm.c : pmm_selftest() case 3/6",
 "验证释放动作使空闲页计数精确回到分配前的值。",
 "释放后查询应等于 free_before，否则返回 6。",
 "启动日志 PASS。"),
("自检用例 5：重复释放被拒绝", "kernel/pmm.c : pmm_selftest() case 5",
 "验证重复释放返回 PMM_EBUSY 而非静默成功。",
 "对已释放地址再次 pmm_free_page，返回值应为 PMM_EBUSY，否则返回 7。",
 "启动日志 PASS。"),
("自检用例 6：连续 4 页分配地址连续", "kernel/pmm.c : pmm_selftest() case 6",
 "验证连续分配返回的块地址对齐、首末页均被占用且可整块释放。",
 "c = pmm_alloc_pages(4)；校验 c 对齐、c 与 c+3*4096 均占用、pmm_free_pages(c,4)==OK。",
 "启动日志 PASS。"),
("自检用例 7：非对齐地址释放被拒绝", "kernel/pmm.c : pmm_selftest() case 7",
 "验证非对齐地址释放返回 PMM_EINVAL。",
 "pmm_free_page(0x1234) 应返回 PMM_EINVAL，否则返回 11。",
 "启动日志 PASS。"),
("自检用例 8：低端内存释放被拒绝", "kernel/pmm.c : pmm_selftest() case 8",
 "验证 1MB 以下页面释放返回 PMM_EBUSY。",
 "pmm_free_page(0x1000) 应返回 PMM_EBUSY，否则返回 12。",
 "启动日志 PASS。"),
("自检失败返回失败用例编号", "kernel/pmm.c : pmm_selftest() 返回值",
 "以非零返回值精确定位失败用例，便于快速排障与复位。",
 "每个用例失败时返回唯一编号（1~13），全部通过返回 0。",
 "启动日志显示 PASS: all 8 test cases succeeded。"),

# ---------------- 三、VGA 文本控制台（80-93）----------------
("VGA 文本模式初始化", "kernel/console.c : con_init()",
 "把控制台初始化为 80x25 彩色文本模式，建立内核与用户可见输出的通道。",
 "复位颜色属性为黑底白字后调用 con_clear 清屏。",
 "启动后屏幕为黑底白字且无残留字符。"),
("VGA 显存直接写入", "kernel/console.c : vga = (u16*)0xB8000",
 "直接写显存实现零依赖输出，不借助任何 BIOS 或外部库。",
 "每个字符单元 16 位，高字节为属性（背景<<4|前景），低字节为 ASCII。",
 "输出字符立即出现在屏幕上，无需刷新。"),
("控制台清屏", "kernel/console.c : con_clear()",
 "用当前属性填充整屏 2000 个字符单元，并把光标归位到左上角。",
 "循环写满 80x25 单元，随后重置 row/col 并同步硬件光标。",
 "调用后屏幕全空且光标位于 (0,0)。"),
("字符输出与自动换行", "kernel/console.c : con_putc()",
 "输出单字符并在行末自动折行，行满屏底自动滚动。",
 "写入 vga[row*80+col] 后 col++；col 达 80 则 col=0、row++。",
 "连续输出 81 个字符时第 81 个落在第二行行首。"),
("屏幕滚动", "kernel/console.c : con_scroll()",
 "屏幕写满后整屏上移一行并在末行补空，保证长输出不丢内容。",
 "把第 1~24 行复制到第 0~23 行，末行用空格填充，光标固定在末行。",
 "输出超过 25 行时内容持续上滚且不越界。"),
("控制字符处理", "kernel/console.c : con_putc()",
 "处理换行、回车、制表、退格四类控制字符，使输出排版可控。",
 "\\n 换行归零列；\\r 仅归零列；\\t 前进到 4 的倍数；\\b 回退并擦除。",
 "输出含 \\r\\n 的字符串时行首不出现多余空行。"),
("硬件光标同步", "kernel/console.c : con_update_hw_cursor()",
 "把软件光标位置写入 CRT 控制器，使屏幕光标与实际输出位置一致。",
 "位置 = row*80+col，经端口 0x3D4/0x3D5 分高低字节写入寄存器 0x0E/0x0F。",
 "输出后屏幕闪烁光标始终跟随最后一个字符。"),
("光标位置设置", "kernel/console.c : con_set_cursor()",
 "按行列直接定位光标，支持后续的界面化输出。",
 "入参越界时裁剪到 79/24，再调用硬件同步。",
 "设置 (10,20) 后光标出现在第 11 行第 21 列。"),
("前景/背景色设置", "kernel/console.c : con_set_color()",
 "设置后续输出的前景与背景颜色，是分级输出与界面配色的基础。",
 "属性字节 = (bg<<4) | (fg&0x0F)，共 16 前景色 × 8 背景色。",
 "切换颜色后新输出字符颜色改变，已有字符不受影响。"),
("十六进制输出", "kernel/console.c : con_put_hex/put_hex32",
 "以固定位宽输出十六进制数值，用于地址、掩码等调试信息。",
 "con_put_hex 按指定位数从高位到低位取半字节映射到 0-9A-F；put_hex32 固定 8 位并加 0x 前缀。",
 "输出 0x0500 显示为 0x00000500。"),
("十进制输出", "kernel/console.c : con_put_dec()",
 "以无符号十进制输出数值，用于容量、页数、计数等人类可读信息。",
 "调用 utoa 转换到栈上缓冲后 con_puts 输出。",
 "输出 32768 显示为 32768。"),
("字符串输出", "kernel/console.c : con_puts()",
 "输出 NUL 结尾字符串，空指针安全。",
 "为 NULL 时直接返回，否则逐字符调用 con_putc。",
 "传入 NULL 不产生崩溃或输出。"),
("printf 子集", "kernel/console.c : con_printf()",
 "提供内核内的格式化输出，支持 %s %c %d %u %x %p %% 六种格式。",
 "基于 va_list 遍历格式串分发；%p 输出 8 位十六进制地址，%% 输出百分号。",
 "各类格式输出与预期一致，未知格式回显原文。"),
("变参支持", "include/stdarg.h : __builtin_va_list",
 "在无标准库环境下提供变参能力，支撑 printf 实现。",
 "用编译器内建 __builtin_va_start/va_arg/va_end 封装为 va_list 宏。",
 "con_printf 可正确取出任意类型实参。"),

# ---------------- 四、字符串与内存操作库（94-109）----------------
("memcpy（对齐优化）", "kernel/string.c : memcpy()",
 "内存拷贝基础函数，在内核各模块间广泛复用。",
 "源目地址对齐相同时先按 4 字节批量拷贝，尾数字节逐字节处理。",
 "对重叠以外的任意长度拷贝结果与逐字节拷贝一致。"),
("memset（字填充优化）", "kernel/string.c : memset()",
 "内存填充基础函数，用于清屏、清页、清结构体。",
 "先对齐到 4 字节，构造 32 位重复模式批量填充，尾数逐字节。",
 "对 4096 字节缓冲区填充后逐字节校验一致。"),
("memmove（重叠处理）", "kernel/string.c : memmove()",
 "支持源目重叠的内存搬移，防止搬运过程自我覆盖。",
 "目的地址低于源地址时前向拷贝，否则从尾部后向拷贝。",
 "对重叠区间搬移结果与临时缓冲区中转结果一致。"),
("memcmp", "kernel/string.c : memcmp()",
 "按字节比较两块内存，用于签名与结构体比对。",
 "逐字节相减，首个不等处返回差值，全等返回 0。",
 "相等返回 0，不等返回非零且符号正确。"),
("memchr", "kernel/string.c : memchr()",
 "在指定长度内查找字节，用于缓冲区扫描。",
 "逐字节比较，命中返回指针，未命中返回 NULL。",
 "命中返回正确地址，未命中返回 NULL。"),
("strlen", "kernel/string.c : strlen()",
 "计算字符串长度，不含结尾 NUL。",
 "从首地址逐字节计数至 NUL。",
 "空串返回 0，\"XOS\" 返回 3。"),
("strcmp", "kernel/string.c : strcmp()",
 "字典序比较字符串，用于命令解析与名称匹配。",
 "逐字符比较至不等或 NUL，返回无符号字节差值。",
 "相等返回 0，\"a\" 与 \"b\" 返回负值。"),
("strncmp", "kernel/string.c : strncmp()",
 "限定长度的字符串比较，用于前缀匹配。",
 "最多比较 n 个字符，提前遇到 NUL 则结束。",
 "前缀相同且长度达 n 时返回 0。"),
("strcpy", "kernel/string.c : strcpy()",
 "字符串拷贝（含结尾 NUL），返回目的地址。",
 "逐字符拷贝直至写入 NUL。",
 "拷贝后源串与目的串 strcmp 为 0。"),
("strncpy（含零填充）", "kernel/string.c : strncpy()",
 "定长字符串拷贝，源串短于 n 时用 NUL 补齐。",
 "先拷贝至多 n 个字符，剩余长度全部填 NUL。",
 "n=8 拷贝 3 字符时后 5 字节为 0。"),
("strcat", "kernel/string.c : strcat()",
 "字符串拼接，把源串追加到目的串末尾。",
 "先定位目的串 NUL 位置，再从该处逐字符追加。",
 "拼接后目的串等于两串直接相连。"),
("strchr", "kernel/string.c : strchr()",
 "查找字符首次出现位置，用于路径与参数解析。",
 "逐字符比较，命中返回指针；查找 NUL 时返回串尾指针。",
 "查找存在的字符返回正确地址，不存在返回 NULL。"),
("strrchr", "kernel/string.c : strrchr()",
 "查找字符最后一次出现位置，常用于取扩展名或末级路径。",
 "遍历全串并持续记录最后一次命中的指针。",
 "多次出现的字符返回最后一次出现的地址。"),
("atoi（含符号与空白处理）", "kernel/string.c : atoi()",
 "字符串转整数，用于解析命令行数字参数。",
 "跳过前导空白，识别正负号，逐位累加至非数字字符。",
 "\"-123\" 返回 -123，\"  45abc\" 返回 45。"),
("utoa（多进制）", "kernel/string.c : utoa()",
 "无符号整数转字符串，支持 2/8/10/16/36 进制。",
 "先反向取余压栈式写入临时缓冲，再反转输出；进制非法时输出空串。",
 "utoa(255, buf, 16) 得到 \"ff\"。"),
("itoa（含负数）", "kernel/string.c : itoa()",
 "有符号整数转字符串，10 进制下正确输出负号。",
 "负数先输出 '-' 再把绝对值交给 utoa。",
 "itoa(-42) 得到 \"-42\"。"),

# ---------------- 五、引导与保护模式（110-120）----------------
("MBR 引导扇区（512 字节 + 魔数）", "boot/boot.S",
 "构建符合 BIOS 规范的 512 字节主引导记录，承担系统启动的第一跳。",
 "加载地址 0x7C00，链接脚本保证输出严格 512 字节且偏移 510-511 为 0x55AA；构建脚本对大小做强校验。",
 "构建产物恰为 512 字节，objdump 校验魔数正确，VirtualBox 成功识别并执行。"),
("BIOS 启动盘号 DL 保存与恢复", "boot/boot.S / boot/stage2.S : boot_drive",
 "保存 BIOS 传入的启动盘号并在每次磁盘调用前恢复，避免被其他中断调用破坏。",
 "进入引导后立即 movb %dl, boot_drive；INT 13h 前 movb boot_drive, %dl。",
 "修复前 Stage2 读内核失败（DL 被 E820 的 EDX 覆盖为 0x50），修复后读取成功。"),
("INT 13h AH=42h 扩展读（LBA 寻址）", "boot/boot.S / boot/stage2.S",
 "使用 BIOS 扩展读接口按 LBA 扇区号读取磁盘，摆脱 CHS 几何限制。",
 "AH=42h，DS:SI 指向磁盘地址包，成功返回 CF=0，失败置 CF=1 并给出 AH 错误码。",
 "在 VirtualBox VDI 磁盘上按 LBA 1 与 LBA 33 读取均成功。"),
("磁盘地址包（DAP）构造与动态改写", "boot/stage2.S : dap_kernel",
 "构造 16 字节磁盘地址包，并在分批读取时动态改写扇区数、目标段、LBA。",
 "布局：尺寸(1) 保留(1) 扇区数(2) 偏移(2) 段(2) LBA(8)；运行时逐字段写入。",
 "每批读取后 DAP 字段正确推进，4 批读取覆盖 LBA 33~160。"),
("Stage2 加载（32 扇区 → 0x7E00）", "boot/boot.S",
 "MBR 从 LBA 1 读取 32 个扇区到 0x0000:0x7E00，装载第二阶段引导。",
 "DAP 指定扇区数 32、目标偏移 0x7E00、段 0x0000，读取成功后远跳转 0x0000:0x7E00。",
 "启动后控制台输出 \"XOS Stage2\"，证明移交成功。"),
("内核加载（分批 32 扇区自动推进）", "boot/stage2.S : load_kernel()",
 "从 LBA 33 读取 128 个扇区装载内核，按 32 扇区一批循环并自动推进目标段与 LBA。",
 "每批读取后 ES 前进 count*32（512/16），LBA 前进 count；剩余扇区数递减至 0 结束。",
 "内核被完整装载到 0x10000，随后成功跳入 kmain 并输出内存信息。"),
("A20 地址线开启（端口 0x92）", "boot/stage2.S : enable_a20()",
 "开启 A20 地址线，使 CPU 能够访问 1MB 以上物理内存。",
 "读端口 0x92，置位 bit1 并清零 bit0（避免触发快速复位），再写回。",
 "进入保护模式后可正常访问 0x100000 以上地址，内存探测统计到 128MB。"),
("GDT 建立（平坦 4GB 描述符）", "boot/stage2.S : gdt",
 "建立全局描述符表，定义空描述符、代码段与数据段，构成平坦内存模型。",
 "空描述符全 0；代码段 0x00CF9A000000FFFF；数据段 0x00CF92000000FFFF，基址 0、段限 4GB、32 位。",
 "保护模式下 CS=0x08、DS=0x10 可访问全 4GB 线性地址空间。"),
("保护模式切换（CR0.PE + 远跳转）", "boot/stage2.S : pm_entry",
 "置位 CR0 的保护模式使能位并远跳转，完成从实模式到 32 位保护模式的切换。",
 "lgdt 装载 GDT 基址与限长，orl $1 到 CR0，ljmp $0x08,$pm_entry 刷新 CS。",
 "跳转后进入 32 位代码，成功以 call 方式进入内核入口 _start。"),
("内核栈建立", "boot/stage2.S / kernel/entry.S",
 "为内核建立 0x9FFFC 处的栈，满足函数调用与局部变量需求。",
 "保护模式下 SS=0x10（平坦）、ESP=0x9FFFC；该区域位于低端 1MB 保留区内，不会被分配器回收。",
 "内核函数调用与 printf 变参压栈均正常，无栈越界。"),
(".bss 段清零", "kernel/entry.S + kernel/linker.ld",
 "内核启动时清零 .bss 段，保证未显式初始化的全局变量从零开始。",
 "链接脚本以 PROVIDE 导出 __bss_start/__bss_end；入口汇编按 4 字节循环写入 0。",
 "符号表校验 __bss_start=0x13080、__bss_end=0x146e0；位图等全局状态初值为 0。"),
]

assert len(FP) == 120, '功能点数量必须为 120，实际 %d' % len(FP)

DETAIL_TPL = (
    "【实现位置】{loc}\n"
    "【功能说明】{desc}\n"
    "【技术实现】{impl}\n"
    "【验收标准】{ac}\n"
    "【验证方式】VirtualBox 启动 build/xos.img，观察控制台输出与 PMM 自检结果"
)


def main():
    if not os.path.exists(XLSX):
        raise SystemExit('文件不存在：%s' % XLSX)

    wb = openpyxl.load_workbook(XLSX)
    ws = wb.active

    # 1) 新增「完成度」列（插到第 7 列，即「是否开发」之后）
    if ws.cell(row=1, column=7).value != '完成度':
        ws.insert_cols(7)
        c = ws.cell(row=1, column=7, value='完成度')
        c.font = Font(bold=True)
        c.alignment = Alignment(horizontal='center', vertical='center')
        c.fill = PatternFill('solid', fgColor='DDEBF7')
        ws.column_dimensions[get_column_letter(7)].width = 10

    hdr = [ws.cell(row=1, column=i).value for i in range(1, ws.max_column + 1)]
    print('表头:', hdr)

    col = {name: i + 1 for i, name in enumerate(hdr)}
    need = ['序号', '功能点名称', '详情描述', '是否开发', '完成度', '更新时间']
    for k in need:
        if k not in col:
            raise SystemExit('缺少列：%s' % k)

    # 2) 回填前 120 行
    updated = 0
    for idx, (name, loc, desc, impl, ac) in enumerate(FP):
        r = 2 + idx                      # 数据从第 2 行开始
        seq = ws.cell(row=r, column=col['序号']).value
        if seq != idx + 1:
            print('  [警告] 第 %d 行序号为 %s，预期 %d' % (r, seq, idx + 1))

        ws.cell(row=r, column=col['功能点名称'], value=name)
        ws.cell(row=r, column=col['详情描述'],
                value=DETAIL_TPL.format(loc=loc, desc=desc, impl=impl, ac=ac))
        ws.cell(row=r, column=col['是否开发'], value='已开发')

        cc = ws.cell(row=r, column=col['完成度'], value=1.0)
        cc.number_format = '0%'
        cc.alignment = Alignment(horizontal='center', vertical='center')

        ws.cell(row=r, column=col['更新时间'], value=STAMP)
        updated += 1

    # 3) 剩余行完成度统一置 0%
    for r in range(2 + len(FP), ws.max_row + 1):
        c = ws.cell(row=r, column=col['完成度'])
        if c.value is None:
            c.value = 0.0
            c.number_format = '0%'

    wb.save(XLSX)
    print('已更新 %d 行；文件已保存：%s' % (updated, XLSX))
    print('文件大小：%d 字节' % os.path.getsize(XLSX))


if __name__ == '__main__':
    main()
